-- ============================================
-- DEPRECATED: Ce fichier est obsolète
-- ============================================
-- Utilisez plutôt le fichier d1-schema.sql qui contient
-- le schéma propre et complet sans duplications.
--
-- Pour réinitialiser la base D1:
--   ./scripts/reset-d1.sh
--
-- Pour appliquer le schéma:
--   ./scripts/setup-d1.sh
